services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: support-bot
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./documents:/app/documents
      - ./test-reports:/app/test-reports
      - ./tests:/app/tests
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PYTHONPATH=/app
      - PYTEST_CURRENT_TEST
      - CHROMA_TELEMETRY_ENABLED=false
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ollama_data:
